version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true" 
    ports:
      - "9200:9200" 
      - "9600:9600" 
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - app-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" 
    depends_on:
      - opensearch
    networks:
      - app-network

volumes:
  opensearch-data:

networks:
  app-network:
    driver: bridge